name: Raise PR with changes

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1  

    - name: Set up GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.tar.gz -o ghcli.tar.gz
        tar xzf ghcli.tar.gz
        sudo mv gh_*/bin/gh /usr/local/bin/
        rm -rf gh_2.0.0_linux_amd64/ ghcli.tar.gz

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # This will get the latest version of Python 3

    - name: Create a new branch and make changes
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'
        branch_name="automated-changes-$(date +'%d%m%Y')"  # create a branch name based on the current day/month/year
        git checkout -b $branch_name

        pip install -r ./util/sgpt/requirements.txt

        python ./util/sgpt/excerpt.py  --dir ./blog/_posts
        python ./util/sgpt/topcta.py  --dir ./blog/_posts

        git add -A
        git commit -m "Automated code changes"
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }} 

    - name: Push changes and create PR
      run: |
        git push --set-upstream origin HEAD  # pushes the newly created branch to origin
        gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
        branch_name="automated-changes-$(date +'%d%m%Y')"  # re-define branch name since we're in a new step
        gh pr create --base main --head $branch_name --title "Automated PR" --body "This is an automated PR."
      env:
        GH_CLI_TOKEN: ${{ secrets.GH_PAT }}
