name: Raise PR with changes

on:
  # run everyday at 12:20 utf ( 8:20 am est) to alert on new posts
  schedule:
    - cron: '* /15 * * *' 

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch all commits/branches

    - name: Set up GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh

    - name: Create a new branch
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'
        branch_name="automated-changes-$(date +'%Y%m%d%H%M%S')"  # create a unique branch name based on the current date/time
        git checkout -b $branch_name

    - name: Make code changes
      run: |
        echo "Some changes" >> some-file.txt  # Make whatever changes you want to your codebase

    - name: Commit and push changes
      run: |
        git add -A
        git commit -m "Automated code changes"
        git push --set-upstream origin HEAD  # pushes the newly created branch to origin

    - name: Raise a PR
      run: |
        gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
        gh pr create --base main --head HEAD --title "Automated PR" --body "This is an automated PR."
      env:
        GH_CLI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
