name: Raise PR with changes

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '* /15 * * *' 

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch all commits/branches

    - name: Set up GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.0.0/gh_2.0.0_linux_amd64.tar.gz -o ghcli.tar.gz
        tar xzf ghcli.tar.gz
        sudo mv gh_*/bin/gh /usr/local/bin/
        rm -rf gh_2.0.0_linux_amd64/ ghcli.tar.gz

    - name: Create a new branch
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'
        branch_name="automated-changes-$(date +'%Y%m%d%H%M%S')"  # create a unique branch name based on the current date/time
        git checkout -b $branch_name
        echo "Some changes" >> some-file.txt  # Make whatever changes you want to your codebase
        git add -A
        git commit -m "Automated code changes"
        git push --set-upstream origin HEAD  # pushes the newly created branch to origin
        gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
        gh pr create --base main --head $branch_name --title "Automated PR" --body "This is an automated PR."
      env:
        GH_CLI_TOKEN: ${{ secrets.GH_PAT }}
